# Generated by Django 2.2.3 on 2019-07-31 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Titular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=255, verbose_name='Sobrenome')),
                ('data_nascimento', models.CharField(max_length=255, verbose_name='Data de nascimento')),
                ('cpf', models.CharField(max_length=255, verbose_name='CPF')),
                ('email', models.EmailField(max_length=255, verbose_name='E-mail')),
                ('senha', models.CharField(max_length=255, verbose_name='Senha')),
                ('telefone', models.CharField(max_length=255, verbose_name='Telefone')),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outros')], max_length=255, verbose_name='Genero')),
                ('data_criacao', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Conta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.FloatField(default=0.0, verbose_name='Saldo')),
                ('numero_conta', models.CharField(max_length=255, verbose_name='Numero da conta')),
                ('agencia', models.CharField(default='235', max_length=255, verbose_name='Agencia')),
                ('nome_banco', models.CharField(default='LiraBank', max_length=255, verbose_name='Nome do banco')),
                ('ativo', models.BooleanField(default=True)),
                ('titular', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='conta.Titular')),
            ],
        ),
    ]
